// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";

export type TurnEnvironmentParams = { environmentId: string, cwd: LegacyAppPathString,
/**
 * Environment-native runtime workspace roots. Omitted inherits the
 * request's top-level `runtimeWorkspaceRoots` fallback.
 */
runtimeWorkspaceRoots?: Array<LegacyAppPathString> | null, };
